### ISSUE TITLE
Ошибка синтаксиса

### ISSUE THREAD

**Issue by breitburg** [theunravelghoul/VKCoinPy#10]
```bash
$ sudo sh start.sh 
Traceback (most recent call last):
  File "vkcoin.py", line 3, in <module>
    from core.manager import VKCoinBotManager
  File "/root/VKCoinPy/core/manager.py", line 112
    wallets: List[BotWallet] = [session.bot.wallet for session in self.bot_sessions]
           ^
SyntaxError: invalid syntax
```

Операционная система: Ubuntu 16.04
Python: 3.5.2

**Comment by awbait** [comment]
Читайте внимательнее требования.
Необходим Python 3.7
