### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by XIshArkIX** [theunravelghoul/VKCoinPy#6]
```
Traceback (most recent call last):
  File "vkcoin.py", line 3, in <module>
    from core.manager import VKCoinBotManager
  File "/home/vdesktop/GitHub/VKCoinPy/core/manager.py", line 121
    wallets: List[BotWallet] = [session.bot.wallet for session in self.bot_sessions]
           ^
SyntaxError: invalid syntax
```
```
#:~/GitHub/VKCoinPy$ python3 -V
Python 3.5.2
```

**Comment by theunravelghoul** [comment]
> #:~/GitHub/VKCoinPy$ python3 -V
> Python 3.5.2

> В требованиях стоит 3.7.
